"""phase 3 domain and authentication schema"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "7a0021405758"
down_revision: str | Sequence[str] | None = "20260618_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=512), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("role", sa.String(length=32), server_default="user", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("email_verified", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("failed_login_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_failed_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "audit_logs",
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=128), nullable=False),
        sa.Column("resource_type", sa.String(length=64), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=True),
        sa.Column("result", sa.String(length=32), nullable=False),
        sa.Column("correlation_id", sa.String(length=128), nullable=False),
        sa.Column("ip_hash", sa.LargeBinary(length=32), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_logs_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(
        "ix_audit_actor_created", "audit_logs", ["actor_user_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(
        op.f("ix_audit_logs_correlation_id"), "audit_logs", ["correlation_id"], unique=False
    )
    op.create_index(
        "ix_audit_resource", "audit_logs", ["resource_type", "resource_id"], unique=False
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("family_id", sa.Uuid(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by_id", sa.Uuid(), nullable=True),
        sa.Column("user_agent_hash", sa.LargeBinary(length=32), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["replaced_by_id"],
            ["refresh_tokens.id"],
            name=op.f("fk_refresh_tokens_replaced_by_id_refresh_tokens"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_refresh_tokens_token_hash")),
    )
    op.create_index(
        op.f("ix_refresh_tokens_expires_at"), "refresh_tokens", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_refresh_tokens_family_id"), "refresh_tokens", ["family_id"], unique=False
    )
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "repositories",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("normalized_clone_url", sa.String(length=2048), nullable=False),
        sa.Column("default_branch", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("latest_revision_id", sa.Uuid(), nullable=True),
        sa.Column("indexing_config", sa.JSON(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by_id"],
            ["users.id"],
            name=op.f("fk_repositories_deleted_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_repositories_owner_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repositories")),
        sa.UniqueConstraint("owner_id", "normalized_clone_url", name="uq_repositories_owner_url"),
    )
    op.create_index(
        op.f("ix_repositories_deleted_at"), "repositories", ["deleted_at"], unique=False
    )
    op.create_index(
        "ix_repositories_owner_status", "repositories", ["owner_id", "status"], unique=False
    )
    op.create_table(
        "repository_revisions",
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("commit_sha", sa.String(length=64), nullable=False),
        sa.Column("ref", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("cloned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("indexed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("file_count", sa.Integer(), nullable=False),
        sa.Column("total_bytes", sa.BigInteger(), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_summary", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "file_count >= 0", name=op.f("ck_repository_revisions_file_count_nonnegative")
        ),
        sa.CheckConstraint(
            "total_bytes >= 0", name=op.f("ck_repository_revisions_total_bytes_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
            name=op.f("fk_repository_revisions_repository_id_repositories"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repository_revisions")),
        sa.UniqueConstraint("repository_id", "commit_sha", name="uq_revision_repository_sha"),
    )
    op.create_index(
        op.f("ix_repository_revisions_repository_id"),
        "repository_revisions",
        ["repository_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_repository_revisions_status"), "repository_revisions", ["status"], unique=False
    )
    with op.batch_alter_table("repositories") as batch_op:
        batch_op.create_foreign_key(
            "fk_repositories_latest_revision_id_repository_revisions",
            "repository_revisions",
            ["latest_revision_id"],
            ["id"],
            ondelete="SET NULL",
        )
    op.create_table(
        "agent_runs",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("revision_id", sa.Uuid(), nullable=True),
        sa.Column("run_type", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("input_summary", sa.Text(), nullable=False),
        sa.Column("model_provider", sa.String(length=64), nullable=False),
        sa.Column("model_identifier", sa.String(length=255), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancellation_metadata", sa.JSON(), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.String(length=1000), nullable=True),
        sa.Column("input_units", sa.BigInteger(), nullable=True),
        sa.Column("output_units", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_agent_runs_owner_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
            name=op.f("fk_agent_runs_repository_id_repositories"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["repository_revisions.id"],
            name=op.f("fk_agent_runs_revision_id_repository_revisions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_runs")),
    )
    op.create_index(
        "ix_agent_runs_owner_status", "agent_runs", ["owner_id", "status"], unique=False
    )
    op.create_index(
        op.f("ix_agent_runs_repository_id"), "agent_runs", ["repository_id"], unique=False
    )
    op.create_index(op.f("ix_agent_runs_run_type"), "agent_runs", ["run_type"], unique=False)
    op.create_index(op.f("ix_agent_runs_status"), "agent_runs", ["status"], unique=False)
    op.create_table(
        "repository_files",
        sa.Column("revision_id", sa.Uuid(), nullable=False),
        sa.Column("normalized_path", sa.String(length=2048), nullable=False),
        sa.Column("language", sa.String(length=64), nullable=True),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("content_hash", sa.String(length=128), nullable=False),
        sa.Column("line_count", sa.Integer(), nullable=False),
        sa.Column("indexing_status", sa.String(length=32), nullable=False),
        sa.Column("excluded_reason", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "line_count >= 0", name=op.f("ck_repository_files_line_count_nonnegative")
        ),
        sa.CheckConstraint("size >= 0", name=op.f("ck_repository_files_size_nonnegative")),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["repository_revisions.id"],
            name=op.f("fk_repository_files_revision_id_repository_revisions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repository_files")),
        sa.UniqueConstraint("revision_id", "normalized_path", name="uq_file_revision_path"),
    )
    op.create_index(
        op.f("ix_repository_files_indexing_status"),
        "repository_files",
        ["indexing_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_repository_files_language"), "repository_files", ["language"], unique=False
    )
    op.create_index(
        op.f("ix_repository_files_revision_id"), "repository_files", ["revision_id"], unique=False
    )
    op.create_table(
        "agent_run_events",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("public_message", sa.String(length=2000), nullable=False),
        sa.Column("private_metadata", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_runs.id"],
            name=op.f("fk_agent_run_events_run_id_agent_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_run_events")),
        sa.UniqueConstraint("run_id", "sequence", name="uq_run_event_sequence"),
    )
    op.create_index(
        op.f("ix_agent_run_events_created_at"), "agent_run_events", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_agent_run_events_event_type"), "agent_run_events", ["event_type"], unique=False
    )
    op.create_table(
        "artifacts",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("artifact_type", sa.String(length=64), nullable=False),
        sa.Column("storage_path", sa.String(length=2048), nullable=True),
        sa.Column("content_reference", sa.String(length=2048), nullable=True),
        sa.Column("media_type", sa.String(length=255), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("checksum", sa.String(length=128), nullable=False),
        sa.Column("artifact_metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_runs.id"],
            name=op.f("fk_artifacts_run_id_agent_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_artifacts")),
    )
    op.create_index(
        op.f("ix_artifacts_artifact_type"), "artifacts", ["artifact_type"], unique=False
    )
    op.create_index(op.f("ix_artifacts_run_id"), "artifacts", ["run_id"], unique=False)
    op.create_table(
        "code_symbols",
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column("symbol_type", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=512), nullable=False),
        sa.Column("qualified_name", sa.String(length=2048), nullable=False),
        sa.Column("start_line", sa.Integer(), nullable=False),
        sa.Column("end_line", sa.Integer(), nullable=False),
        sa.Column("signature", sa.Text(), nullable=True),
        sa.Column("parent_symbol_id", sa.Uuid(), nullable=True),
        sa.Column("symbol_metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("end_line >= start_line", name=op.f("ck_code_symbols_line_range_valid")),
        sa.CheckConstraint("start_line > 0", name=op.f("ck_code_symbols_start_line_positive")),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["repository_files.id"],
            name=op.f("fk_code_symbols_file_id_repository_files"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_symbol_id"],
            ["code_symbols.id"],
            name=op.f("fk_code_symbols_parent_symbol_id_code_symbols"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_code_symbols")),
    )
    op.create_index(op.f("ix_code_symbols_file_id"), "code_symbols", ["file_id"], unique=False)
    op.create_index(op.f("ix_code_symbols_name"), "code_symbols", ["name"], unique=False)
    op.create_index(
        op.f("ix_code_symbols_symbol_type"), "code_symbols", ["symbol_type"], unique=False
    )
    op.create_index(
        "ix_symbols_file_qualified_name",
        "code_symbols",
        ["file_id", "qualified_name"],
        unique=False,
    )
    op.create_table(
        "patches",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("base_commit_sha", sa.String(length=64), nullable=False),
        sa.Column("unified_diff", sa.Text(), nullable=False),
        sa.Column("diff_checksum", sa.String(length=128), nullable=False),
        sa.Column("affected_file_count", sa.Integer(), nullable=False),
        sa.Column("approval_metadata", sa.JSON(), nullable=True),
        sa.Column("validation_metadata", sa.JSON(), nullable=True),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reverted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_runs.id"],
            name=op.f("fk_patches_run_id_agent_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_patches")),
        sa.UniqueConstraint("diff_checksum", name=op.f("uq_patches_diff_checksum")),
    )
    op.create_index(op.f("ix_patches_run_id"), "patches", ["run_id"], unique=False)
    op.create_index(op.f("ix_patches_status"), "patches", ["status"], unique=False)
    op.create_table(
        "test_executions",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("patch_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("command_identifier", sa.String(length=255), nullable=False),
        sa.Column("exit_code", sa.Integer(), nullable=True),
        sa.Column("duration_ms", sa.BigInteger(), nullable=True),
        sa.Column("stdout", sa.Text(), nullable=True),
        sa.Column("stderr", sa.Text(), nullable=True),
        sa.Column("resource_summary", sa.JSON(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["patch_id"],
            ["patches.id"],
            name=op.f("fk_test_executions_patch_id_patches"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_runs.id"],
            name=op.f("fk_test_executions_run_id_agent_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_test_executions")),
    )
    op.create_index(op.f("ix_test_executions_run_id"), "test_executions", ["run_id"], unique=False)
    op.create_index(op.f("ix_test_executions_status"), "test_executions", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_test_executions_status"), table_name="test_executions")
    op.drop_index(op.f("ix_test_executions_run_id"), table_name="test_executions")
    op.drop_table("test_executions")
    op.drop_index(op.f("ix_patches_status"), table_name="patches")
    op.drop_index(op.f("ix_patches_run_id"), table_name="patches")
    op.drop_table("patches")
    op.drop_index("ix_symbols_file_qualified_name", table_name="code_symbols")
    op.drop_index(op.f("ix_code_symbols_symbol_type"), table_name="code_symbols")
    op.drop_index(op.f("ix_code_symbols_name"), table_name="code_symbols")
    op.drop_index(op.f("ix_code_symbols_file_id"), table_name="code_symbols")
    op.drop_table("code_symbols")
    op.drop_index(op.f("ix_artifacts_run_id"), table_name="artifacts")
    op.drop_index(op.f("ix_artifacts_artifact_type"), table_name="artifacts")
    op.drop_table("artifacts")
    op.drop_index(op.f("ix_agent_run_events_event_type"), table_name="agent_run_events")
    op.drop_index(op.f("ix_agent_run_events_created_at"), table_name="agent_run_events")
    op.drop_table("agent_run_events")
    op.drop_index(op.f("ix_repository_files_revision_id"), table_name="repository_files")
    op.drop_index(op.f("ix_repository_files_language"), table_name="repository_files")
    op.drop_index(op.f("ix_repository_files_indexing_status"), table_name="repository_files")
    op.drop_table("repository_files")
    op.drop_index(op.f("ix_agent_runs_status"), table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_run_type"), table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_repository_id"), table_name="agent_runs")
    op.drop_index("ix_agent_runs_owner_status", table_name="agent_runs")
    op.drop_table("agent_runs")
    with op.batch_alter_table("repositories") as batch_op:
        batch_op.drop_constraint(
            "fk_repositories_latest_revision_id_repository_revisions", type_="foreignkey"
        )
    op.drop_index(op.f("ix_repository_revisions_status"), table_name="repository_revisions")
    op.drop_index(op.f("ix_repository_revisions_repository_id"), table_name="repository_revisions")
    op.drop_table("repository_revisions")
    op.drop_index("ix_repositories_owner_status", table_name="repositories")
    op.drop_index(op.f("ix_repositories_deleted_at"), table_name="repositories")
    op.drop_table("repositories")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_family_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_expires_at"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index("ix_audit_resource", table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_correlation_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_index("ix_audit_actor_created", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
